# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox
from blackfox.api.data_set_api import DataSetApi  # noqa: E501
from blackfox.rest import ApiException


class TestDataSetApi(unittest.TestCase):
    """DataSetApi unit test stubs"""

    def setUp(self):
        self.api = blackfox.api.data_set_api.DataSetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get(self):
        """Test case for get

        Download dataset file (*.csv)  # noqa: E501
        """
        pass

    def test_head(self):
        """Test case for head

        Check if csv file exist  # noqa: E501
        """
        pass

    def test_post(self):
        """Test case for post

        Upload csv file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
