# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import black_fox_client
from black_fox_client.models.optimization_engine_config import OptimizationEngineConfig  # noqa: E501
from black_fox_client.rest import ApiException


class TestOptimizationEngineConfig(unittest.TestCase):
    """OptimizationEngineConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptimizationEngineConfig(self):
        """Test OptimizationEngineConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = black_fox_client.models.optimization_engine_config.OptimizationEngineConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
