# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import black_fox_client
from black_fox_client.models.layer_config_keras_activation_function import LayerConfigKerasActivationFunction  # noqa: E501
from black_fox_client.rest import ApiException


class TestLayerConfigKerasActivationFunction(unittest.TestCase):
    """LayerConfigKerasActivationFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLayerConfigKerasActivationFunction(self):
        """Test LayerConfigKerasActivationFunction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = black_fox_client.models.layer_config_keras_activation_function.LayerConfigKerasActivationFunction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
