# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox
from blackfox.models.range_map import RangeMap  # noqa: E501
from blackfox.rest import ApiException


class TestRangeMap(unittest.TestCase):
    """RangeMap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRangeMap(self):
        """Test RangeMap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blackfox.models.range_map.RangeMap()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
