# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox
from blackfox.models.hidden_layer_config_keras_activation_function import HiddenLayerConfigKerasActivationFunction  # noqa: E501
from blackfox.rest import ApiException


class TestHiddenLayerConfigKerasActivationFunction(unittest.TestCase):
    """HiddenLayerConfigKerasActivationFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHiddenLayerConfigKerasActivationFunction(self):
        """Test HiddenLayerConfigKerasActivationFunction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blackfox.models.hidden_layer_config_keras_activation_function.HiddenLayerConfigKerasActivationFunction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
