# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox
from blackfox.models.keras_training_config import KerasTrainingConfig  # noqa: E501
from blackfox.rest import ApiException


class TestKerasTrainingConfig(unittest.TestCase):
    """KerasTrainingConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKerasTrainingConfig(self):
        """Test KerasTrainingConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blackfox.models.keras_training_config.KerasTrainingConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
