# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import black_fox_client
from black_fox_client.api.training_api import TrainingApi  # noqa: E501
from black_fox_client.rest import ApiException


class TestTrainingApi(unittest.TestCase):
    """TrainingApi unit test stubs"""

    def setUp(self):
        self.api = black_fox_client.api.training_api.TrainingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post(self):
        """Test case for post

        """
        pass


if __name__ == '__main__':
    unittest.main()
