# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import black_fox_client
from black_fox_client.api.optimization_api import OptimizationApi  # noqa: E501
from black_fox_client.rest import ApiException


class TestOptimizationApi(unittest.TestCase):
    """OptimizationApi unit test stubs"""

    def setUp(self):
        self.api = black_fox_client.api.optimization_api.OptimizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        """
        pass

    def test_get(self):
        """Test case for get

        """
        pass

    def test_get_0(self):
        """Test case for get_0

        """
        pass

    def test_post_async(self):
        """Test case for post_async

        """
        pass

    def test_post_async_0(self):
        """Test case for post_async_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
