# coding: utf-8

# flake8: noqa
"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from black_fox_client.models.hidden_layer_config_keras_activation_function import HiddenLayerConfigKerasActivationFunction
from black_fox_client.models.keras_optimization_config import KerasOptimizationConfig
from black_fox_client.models.keras_optimization_status import KerasOptimizationStatus
from black_fox_client.models.keras_optimized_network import KerasOptimizedNetwork
from black_fox_client.models.keras_training_config import KerasTrainingConfig
from black_fox_client.models.layer_config_keras_activation_function import LayerConfigKerasActivationFunction
from black_fox_client.models.optimization_engine_config import OptimizationEngineConfig
from black_fox_client.models.prediction_array_config import PredictionArrayConfig
from black_fox_client.models.prediction_file_config import PredictionFileConfig
from black_fox_client.models.range import Range
from black_fox_client.models.range_map import RangeMap
from black_fox_client.models.trained_network import TrainedNetwork
