# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from black_fox_client.models.range import Range  # noqa: F401,E501


class RangeMap(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_range': 'Range',
        'scaled_range': 'Range'
    }

    attribute_map = {
        'data_range': 'dataRange',
        'scaled_range': 'scaledRange'
    }

    def __init__(self, data_range=None, scaled_range=None):  # noqa: E501
        """RangeMap - a model defined in Swagger"""  # noqa: E501

        self._data_range = None
        self._scaled_range = None
        self.discriminator = None

        if data_range is not None:
            self.data_range = data_range
        if scaled_range is not None:
            self.scaled_range = scaled_range

    @property
    def data_range(self):
        """Gets the data_range of this RangeMap.  # noqa: E501


        :return: The data_range of this RangeMap.  # noqa: E501
        :rtype: Range
        """
        return self._data_range

    @data_range.setter
    def data_range(self, data_range):
        """Sets the data_range of this RangeMap.


        :param data_range: The data_range of this RangeMap.  # noqa: E501
        :type: Range
        """

        self._data_range = data_range

    @property
    def scaled_range(self):
        """Gets the scaled_range of this RangeMap.  # noqa: E501


        :return: The scaled_range of this RangeMap.  # noqa: E501
        :rtype: Range
        """
        return self._scaled_range

    @scaled_range.setter
    def scaled_range(self, scaled_range):
        """Sets the scaled_range of this RangeMap.


        :param scaled_range: The scaled_range of this RangeMap.  # noqa: E501
        :type: Range
        """

        self._scaled_range = scaled_range

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RangeMap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
