# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InputWindowConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'step': 'int',
        'aggregation_type': 'str',
        'window': 'int',
        'shift': 'int'
    }

    attribute_map = {
        'step': 'step',
        'aggregation_type': 'aggregationType',
        'window': 'window',
        'shift': 'shift'
    }

    def __init__(self, step=1, aggregation_type='None', window=1, shift=0):  # noqa: E501
        """InputWindowConfig - a model defined in Swagger"""  # noqa: E501

        self._step = None
        self._aggregation_type = None
        self._window = None
        self._shift = None
        self.discriminator = None

        if step is not None:
            self.step = step
        if aggregation_type is not None:
            self.aggregation_type = aggregation_type
        if window is not None:
            self.window = window
        if shift is not None:
            self.shift = shift

    @property
    def step(self):
        """Gets the step of this InputWindowConfig.  # noqa: E501


        :return: The step of this InputWindowConfig.  # noqa: E501
        :rtype: int
        """
        return self._step

    @step.setter
    def step(self, step):
        """Sets the step of this InputWindowConfig.


        :param step: The step of this InputWindowConfig.  # noqa: E501
        :type: int
        """

        self._step = step

    @property
    def aggregation_type(self):
        """Gets the aggregation_type of this InputWindowConfig.  # noqa: E501


        :return: The aggregation_type of this InputWindowConfig.  # noqa: E501
        :rtype: str
        """
        return self._aggregation_type

    @aggregation_type.setter
    def aggregation_type(self, aggregation_type):
        """Sets the aggregation_type of this InputWindowConfig.


        :param aggregation_type: The aggregation_type of this InputWindowConfig.  # noqa: E501
        :type: str
        """
        allowed_values = ["Avg", "Sum", "None"]  # noqa: E501
        if aggregation_type not in allowed_values:
            raise ValueError(
                "Invalid value for `aggregation_type` ({0}), must be one of {1}"  # noqa: E501
                .format(aggregation_type, allowed_values)
            )

        self._aggregation_type = aggregation_type

    @property
    def window(self):
        """Gets the window of this InputWindowConfig.  # noqa: E501


        :return: The window of this InputWindowConfig.  # noqa: E501
        :rtype: int
        """
        return self._window

    @window.setter
    def window(self, window):
        """Sets the window of this InputWindowConfig.


        :param window: The window of this InputWindowConfig.  # noqa: E501
        :type: int
        """

        self._window = window

    @property
    def shift(self):
        """Gets the shift of this InputWindowConfig.  # noqa: E501


        :return: The shift of this InputWindowConfig.  # noqa: E501
        :rtype: int
        """
        return self._shift

    @shift.setter
    def shift(self, shift):
        """Sets the shift of this InputWindowConfig.


        :param shift: The shift of this InputWindowConfig.  # noqa: E501
        :type: int
        """

        self._shift = shift

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InputWindowConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
