# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from blackfox.models.range import Range  # noqa: F401,E501


class InputConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'range': 'Range',
        'is_optional': 'bool'
    }

    attribute_map = {
        'range': 'range',
        'is_optional': 'isOptional'
    }

    def __init__(self, range=None, is_optional=False):  # noqa: E501
        """InputConfig - a model defined in Swagger"""  # noqa: E501

        self._range = None
        self._is_optional = False
        self.discriminator = None

        if range is not None:
            self.range = range
        if is_optional is not None:
            self.is_optional = is_optional

    @property
    def range(self):
        """Gets the range of this InputConfig.  # noqa: E501


        :return: The range of this InputConfig.  # noqa: E501
        :rtype: Range
        """
        return self._range

    @range.setter
    def range(self, range):
        """Sets the range of this InputConfig.


        :param range: The range of this InputConfig.  # noqa: E501
        :type: Range
        """

        self._range = range

    @property
    def is_optional(self):
        """Gets the is_optional of this InputConfig.  # noqa: E501


        :return: The is_optional of this InputConfig.  # noqa: E501
        :rtype: bool
        """
        return self._is_optional

    @is_optional.setter
    def is_optional(self, is_optional):
        """Sets the is_optional of this InputConfig.


        :param is_optional: The is_optional of this InputConfig.  # noqa: E501
        :type: bool
        """

        self._is_optional = is_optional

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InputConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
